### PR TITLE
Changed source from github master to .

### PR DESCRIPTION
**Pull request by marzipankaiser**
Change the `default.nix` to use . (this directory) as source instead of the github master branch.

### CODE REVIEW

**Comment by marzipankaiser** [comment]
Does anyone else use the `default.nix`? If yes, please test if this works for you.

**Comment by marzipankaiser** [comment]
@haslersn @ayguenef ? Nutzt das jemand von euch?

**Comment by haslersn** [comment]
No

**Comment by ayguenef** [comment]
Nah

**Comment by marzipankaiser** [comment]
Good, since I seam to be the only one using this and it works for me

**Pull request merged**
